server:
  port: 8083

spring:
  application:
    name: exhibition-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${EXHIBITION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka