server:
  port: ${EXHIBITION_SERVICE_PORT:9004}

spring:
  application:
    name: EXHIBITION-SERVICE

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${EXHIBITION_STALL_STATUS_GROUP:exhibition-stall-status}
      auto-offset-reset: earliest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${EXHIBITION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.exhibition.exhibition_service.controller

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:9001/eureka}

app:
  kafka:
    topics:
      payment-success: ${PAYMENT_SUCCESS_TOPIC:payment.success}
      stall-status-update: ${STALL_STATUS_UPDATE_TOPIC:stall.status.update}
      stall-status-events: ${STALL_STATUS_EVENTS_TOPIC:stall.status.events}
