server:
  port: ${NOTIFICATION_SERVICE_PORT:8084}

spring:
  application:
    name: NOTIFICATION-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${NOTIFICATION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_EMAIL}
    password: ${NOTIFICATION_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8070/eureka}
